version: '3.8'
services:
    db:
        image: postgres
        volumes:
            - ./tmp/pg:/var/lib/postgresql/data
        ports:
            - 5433:5433
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=shn-platform
